/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "NodoCliente.h"

bool_t
xdr_paths (XDR *xdrs, paths *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->pathDFS, 64,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->filename, 64,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
