/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NODOCLIENTE_H_RPCGEN
#define _NODOCLIENTE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct paths {
	char pathDFS[64];
	char filename[64];
};
typedef struct paths paths;

#define NODOCLIENTE 0x20000003
#define VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define subir 1
extern  int * subir_1(paths *, CLIENT *);
extern  int * subir_1_svc(paths *, struct svc_req *);
#define bajar 2
extern  char ** bajar_1(char **, CLIENT *);
extern  char ** bajar_1_svc(char **, struct svc_req *);
extern int nodocliente_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define subir 1
extern  int * subir_1();
extern  int * subir_1_svc();
#define bajar 2
extern  char ** bajar_1();
extern  char ** bajar_1_svc();
extern int nodocliente_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_paths (XDR *, paths*);

#else /* K&R C */
extern bool_t xdr_paths ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NODOCLIENTE_H_RPCGEN */
